### ISSUE TITLE
Default value callback signature is incorrect

### ISSUE THREAD

**Issue by leonderijke** [mikestopcontinues/metalsmith-validate#1]
The README states that the default callback will be called with `file, data`, but it is only called with `data[key]`, which is obviously `undefined` in this case.

See https://github.com/mikestopcontinues/metalsmith-validate/commit/adacf42e748bcf6512702ede2779d10ad54975bf#diff-6d186b954a58d5bb740f73d84fe39073R72

**Comment by mikestopcontinues** [comment]
Thanks! Please confirm the update works. :)

**Comment by leonderijke** [comment]
The update isn't published yet on NPM? I tested it locally, it works.

**Comment by mikestopcontinues** [comment]
Thanks Leon, it's been published!
